version: '3'
services:
    app:
        container_name: fcwr
        restart: always
        build: .
        volumes:
            - ./server:/fcwr
        ports:
            - 3000:3000
        command: sh -c "export FLASK_DEBUG=1 && python serve.py"
        environment:
            - PYTHONUNBUFFERED=1
